
create table users (
    id integer primary key generated by default as identity,
    username text unique not null,
    user_password text not null,
    first_name text not null,
    last_name text not null,
    email text unique not null,
    date_joined timestamptz default now() not null
);